### ISSUE TITLE
Create New Page Binding to Current Page Type

### ISSUE THREAD

**Issue by 192Iridium77** [whpptjs/whppt-nuxt#14]
**Describe the bug**
When creating a new page, the pageType value that is v-model'ed to the page Type select is populated by the current page that you have selected. Users that do not select an option from this select and instead set the slug and try to create are met with an error "Missing Template". 

Whppt version: @whppt/nuxt@2.0.0-rc17
Nuxt version: @nuxt/cli v2.14.6
Node version: v14.12.0

**To Reproduce**
1. Go to create a new page
2. Leave the page type select bound as whatever page type you're currently navigated onto. Fill in the slug and hit create.
4. See error "Missing Template"

**Expected behavior**
Select should be empty, perhaps the create button disabled, or some kind of message indicating that the user needs to fill in the select.

**Screenshots**
![image](https://user-images.githubusercontent.com/25541636/98900561-f2955500-2501-11eb-97bb-1b025c824e2e.png)

**Desktop (please complete the following information):**
 - OS: Mac 10.15.5 Catalina
 - Browser Chrome
 - Version 86

Removing this line solves the issue as far as I can tell:
`  mounted() {
    if (this.page && this.page.pageType) this.pageForm.pageType = this.page.pageType;
  },`

**Comment by lvcasjm** [comment]
Thanks for the detailed issue as well as the pull request, the PR has been merged in and this issue has been fixed.

see [here](https://github.com/whpptjs/whppt-nuxt/commit/51672d28763950646af718a7905bcaf61b815c16).
