### ISSUE TITLE
All 404 error are overridden by 401s

### ISSUE THREAD

**Issue by xyzzyxyzzy0077** [whpptjs/whppt-nuxt#21]
**Describe the bug**

Whppt version:2.0.0-rc23
Nuxt version:2.14.7
Node version:14.15.0

**To Reproduce**
Going to any URL that hasn't been created, got error code 401 instead of 404

**Expected behavior**
Getting 404 error when pages are not found

**Comment by lvcasjm** [comment]
Hey, this one is an issue with the @whppt/api-express project that was recently resolved, i'm going to close this one.

Cheers
