### ISSUE TITLE
Cannot add component from the list to the page after hitting Save in the editor

### ISSUE THREAD

**Issue by xyzzyxyzzy0077** [whpptjs/whppt-nuxt#48]
**Describe the bug**

@whppt/nuxt version: 2.0.0-rc44
@whppt/api-express version: 2.0.0-rc27
nuxt version: 2.14.12
node version: 14.15.0

**To Reproduce**
1. Add a component to a page
2. Click save in the editor
3. Cannot add component from the list again

**Expected behavior**
Should still can add components to the page

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 (19H524)
 - Browser: Chrome
 - Version: 89.0.4389.114

**Smartphone (please complete the following information):**
N/A

**Comment by lvcasjm** [comment]
This one has been resolved now, see [here](https://github.com/whpptjs/whppt-nuxt/commit/4783bb48bdc2584db76e9225f332d924130e2195). This was also released in [@whppt/nuxt@2.0.0-rc45](https://www.npmjs.com/package/@whppt/nuxt/v/2.0.0-rc45).

Thanks for raising this as an issue.
