### ISSUE TITLE
Widget movement / delete buttons not working

### ISSUE THREAD

**Issue by BGillyVII** [whpptjs/whppt-nuxt#5]
**Describe the bug**
Selecting a component in the contents array. i am unable to move an item up/down or even delete an item from the contents array.

The buttons on the left widget do nothing.

**To Reproduce**
1. Create a new page.
2. Add two components to the contents array
3. Try to move the 2nd component to the first spot or even delete it. 
4. Nothing happens

**Expected behavior**
I expect the delete button to delete the selected component.

I expect the movement arrows to move the selected component

**Comment by lvcasjm** [comment]
This issue has been resolved. See [here](https://github.com/whpptjs/whppt-nuxt/commit/5cb97245f2fa85c53786bf240c48b1fe1fc44a0c).

It is currently awaiting the next release.
