### ISSUE TITLE
Component margin control.

### ISSUE THREAD

**Issue by BGillyVII** [whpptjs/whppt-nuxt#6]
**Describe the Feature Request**
The ability to dynamically control margins per component in the components array

**Describe Preferred Solution**

Editors get a margin input for mobile/desktop

**Comment by lvcasjm** [comment]
Most of the work regarding this has been done, see [here](https://github.com/whpptjs/whppt-nuxt/commit/ba5b0d9f02d6655db462cd7baa3d596e44c1acde). 

Remaining for this feature will be how the classes will be added to elements that require the controls.

**Comment by lvcasjm** [comment]
This has been implemented and is active in the @next published version of @whppt/nuxt. The classes follow tailwinds padding and margin concepts eg. mt-4 or pb-8.
