### ISSUE TITLE
Site Settings - menu navigation.

### ISSUE THREAD

**Issue by BGillyVII** [whpptjs/whppt-nuxt#8]
**Describe the bug**
In the site settings popup when i select a new tab (a new custom tab in my case) the mounted on the new selected tab gets called 10 times.  

Whppt version: 2.0.0-rc9
Nuxt version: 2.14.3
Node version:

**Expected behavior**
It to only call mounted one.

**Comment by lvcasjm** [comment]
This has been fixed, see [here](https://github.com/whpptjs/whppt-nuxt/commit/757460ea503a08ae24a759b479c530cd989831ab).
